### ISSUE TITLE
bug in Haptic_Driver.cpp line 405

### ISSUE THREAD

**Issue by TonyLHansen** [sparkfun/SparkFun_Qwiic_Haptic_Driver_DA7280_Arduino_Library#1]
https://github.com/sparkfun/SparkFun_Qwiic_Haptic_Driver_DA7280_Arduino_Library/blob/dbc04559235a21e447676c4c8bb78636353928c7/src/Haptic_Driver.cpp#L405
"==" should be "="

**Comment by edspark** [comment]
Absolutely correct, fixed [here](https://github.com/sparkfun/SparkFun_Qwiic_Haptic_Driver_DA7280_Arduino_Library/commit/af7d5e2b623370a460981eabe181d3716a2afd64)
