### ISSUE TITLE
bug in Haptic_Driver.h line 13

### ISSUE THREAD

**Issue by TonyLHansen** [sparkfun/SparkFun_Qwiic_Haptic_Driver_DA7280_Arduino_Library#2]
https://github.com/sparkfun/SparkFun_Qwiic_Haptic_Driver_DA7280_Arduino_Library/blob/dbc04559235a21e447676c4c8bb78636353928c7/src/Haptic_Driver.h#L130

SEG_CTL1 should be SEQ_CTL1

**Comment by edspark** [comment]
Thanks again, good eye! Fixed [here](https://github.com/sparkfun/SparkFun_Qwiic_Haptic_Driver_DA7280_Arduino_Library/commit/af7d5e2b623370a460981eabe181d3716a2afd64)
